[profile.default]
fs_permissions = [{ access = "read-write", path = "./"}]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test/foundry'
cache_path  = 'forge-cache'


[rpc_endpoints]
# The RPC URLs are modified versions of the default for testing initialization.
ConsensysZkEVM_goerli = "${ConsensysZKevm_GOERLI_RPC_URL}"
[fmt]
# These are all the `forge fmt` defaults.
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = 'long'
multiline_func_header = 'attributes_first'
quote_style = 'double'
number_underscore = 'preserve'
single_line_statement_blocks = 'preserve'
ignore = ["src/console.sol", "src/console2.sol"]